import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import authRouter from './auth.js';
import productsRouter from './routes/products.js';
import quotationsRouter from './routes/quotations.js';
import companiesRouter from './routes/companies.js';
import paymentsRouter from './routes/payments.js';
import webhooksRouter from './routes/webhooks.js';
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/auth', authRouter);
app.use('/api/products', productsRouter);
app.use('/api/quotations', quotationsRouter);
app.use('/api/companies', companiesRouter);
app.use('/api/payments', paymentsRouter);
app.use('/api/webhooks', webhooksRouter);
app.get('/', (req, res) => res.json({ ok: true, message: 'BuildQuote API' }));
const port = process.env.PORT || 4000;
app.listen(port, () => { console.log('Server listening on', port); });
